id = "wattle"
name = "Wattle"
description = "Syntax highlighting and language support for the Wattle programming language"
version = "0.3.0"
schema_version = 1
authors = ["zmscode"]
repository = "https://github.com/zmscode/zed-wattle"

themes = []
icon_themes = []
languages = ["languages/wattle"]
capabilities = []

[lib]

[grammars.wattle]
repository = "https://github.com/zmscode/tree-sitter-wattle"
rev = "1d6778eb0560dfbe19a43b8416b63a67db8a702a"

[language_servers]
[context_servers]
[agent_servers]
[slash_commands]
