id = "wattle"
name = "Wattle"
description = "Syntax highlighting and language support for the Wattle programming language"
version = "0.3.0"
schema_version = 1
authors = ["zmscode"]
repository = "https://github.com/zmscode/zed-wattle"

[grammars.wattle]
repository = "https://github.com/zmscode/tree-sitter-wattle"
rev = "bdaa985f64520fc325673d9b4ba5623a53b0d3c6"
